import { useState, useEffect, useRef } from 'react';
import toast from 'react-hot-toast';
import { Upload, X, FileText, Image } from 'lucide-react';
import { supabase } from '../lib/supabase';
import { useCompany } from '../context/CompanyContext';
import { useAuth } from '../context/AuthProvider';
import type { Transaction, Customer, Project, Category } from '../lib/supabase';

interface TransactionFormProps {
  transaction?: Transaction;
  onSubmit: (data: Partial<Transaction>) => Promise<void>;
  onCancel: () => void;
  customers: Customer[];
  projects: Project[];
}

export default function TransactionForm({ transaction, onSubmit, onCancel, customers, projects }: TransactionFormProps) {
  const { selectedCompany } = useCompany();
  const { user } = useAuth();
  const fileInputRef = useRef<HTMLInputElement>(null);
  const [categories, setCategories] = useState<Category[]>([]);
  const [isLoadingCategories, setIsLoadingCategories] = useState(true);
  const [activeTab, setActiveTab] = useState<'einnahme' | 'ausgabe'>(transaction?.type || 'ausgabe');
  const [transactionNumber, setTransactionNumber] = useState(transaction?.transaction_number || '');
  const [date, setDate] = useState(transaction?.date || new Date().toISOString().split('T')[0]);
  const [amount, setAmount] = useState(transaction?.amount.toString() || '');
  const [categoryId, setCategoryId] = useState(transaction?.category || '');
  const [description, setDescription] = useState(transaction?.description || '');
  const [customerId, setCustomerId] = useState(transaction?.customer_id || '');
  const [projectId, setProjectId] = useState(transaction?.project_id || '');
  const [tags, setTags] = useState<string[]>(transaction?.tags || []);
  const [tagInput, setTagInput] = useState('');
  const [loading, setLoading] = useState(false);

  // Receipt upload state
  const [receiptFile, setReceiptFile] = useState<File | null>(null);
  const [existingReceiptUrl, setExistingReceiptUrl] = useState<string | null>(transaction?.receipt_url || null);
  const [uploadingReceipt, setUploadingReceipt] = useState(false);

  // Fetch categories from database
  useEffect(() => {
    const fetchCategories = async () => {
      if (!selectedCompany) return;

      try {
        setIsLoadingCategories(true);
        const { data, error } = await supabase
          .from('categories')
          .select('*')
          .eq('company_id', selectedCompany.id)
          .eq('is_active', true)
          .order('sort_order', { ascending: true });

        if (error) throw error;
        setCategories(data || []);

        // Set default category if none selected
        if (!categoryId && data && data.length > 0) {
          const typeForTab = activeTab === 'einnahme' ? 'income' : 'expense';
          const defaultCat = data.find(c => c.type === typeForTab);
          if (defaultCat) {
            setCategoryId(defaultCat.id);
          }
        }
      } catch (err) {
        console.error('Error fetching categories:', err);
      } finally {
        setIsLoadingCategories(false);
      }
    };

    fetchCategories();
  }, [selectedCompany]);

  // Group categories by type
  const incomeCategories = categories.filter(c => c.type === 'income');
  const expenseCategories = categories.filter(c => c.type === 'expense');

  // Handle category change - auto-set type based on category
  const handleCategoryChange = (newCategoryId: string) => {
    setCategoryId(newCategoryId);
    const selectedCat = categories.find(c => c.id === newCategoryId);
    if (selectedCat) {
      const newType = selectedCat.type === 'income' ? 'einnahme' : 'ausgabe';
      setActiveTab(newType);
    }
  };

  // Handle tab change - update category to first of that type
  const handleTabChange = (newTab: 'einnahme' | 'ausgabe') => {
    setActiveTab(newTab);
    const targetCategories = newTab === 'einnahme' ? incomeCategories : expenseCategories;
    if (targetCategories.length > 0) {
      setCategoryId(targetCategories[0].id);
    }
  };

  // Removed auto-generation logic (Phase 3.4)
  // Transaction numbers are now auto-generated by database trigger
  // See migration: 20260215_transaction_auto_increment.sql

  const handleSubmit = async (e: React.FormEvent, saveAndNew = false) => {
    e.preventDefault();
    setLoading(true);

    // Get category name for storage (backward compatible with string category field)
    const selectedCategory = categories.find(c => c.id === categoryId);
    const categoryName = selectedCategory?.name || null;

    try {
      // Upload receipt if a new file was selected
      let receiptUrl = existingReceiptUrl;
      if (receiptFile) {
        receiptUrl = await uploadReceipt();
      }

      await onSubmit({
        type: activeTab,
        transaction_number: transactionNumber || null, // Let DB trigger generate if empty
        date,
        amount: parseFloat(amount),
        category: categoryName,
        description: description || null,
        customer_id: customerId || null,
        project_id: projectId || null,
        tags: tags.length > 0 ? tags : null,
        receipt_url: receiptUrl,
      });

      if (saveAndNew) {
        // Reset form - keep current type and select first category of that type
        const currentTypeCategories = activeTab === 'einnahme' ? incomeCategories : expenseCategories;
        setTransactionNumber('');
        setAmount('');
        setDescription('');
        setCategoryId(currentTypeCategories[0]?.id || '');
        setCustomerId('');
        setProjectId('');
        setTags([]);
        setReceiptFile(null);
        setExistingReceiptUrl(null);
        if (fileInputRef.current) {
          fileInputRef.current.value = '';
        }
      } else {
        onCancel();
      }
    } catch (error) {
      console.error('Error saving transaction:', error);
    } finally {
      setLoading(false);
    }
  };

  const addTag = () => {
    if (tagInput.trim() && !tags.includes(tagInput.trim())) {
      setTags([...tags, tagInput.trim()]);
      setTagInput('');
    }
  };

  const removeTag = (tagToRemove: string) => {
    setTags(tags.filter(tag => tag !== tagToRemove));
  };

  // Receipt file handling
  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      // Validate file type
      const allowedTypes = ['application/pdf', 'image/jpeg', 'image/png', 'image/webp'];
      if (!allowedTypes.includes(file.type)) {
        toast.error('Bitte wählen Sie eine PDF- oder Bilddatei (JPG, PNG, WebP).');
        return;
      }
      // Validate file size (max 10MB)
      if (file.size > 10 * 1024 * 1024) {
        toast.error('Die Datei darf maximal 10 MB gross sein.');
        return;
      }
      setReceiptFile(file);
      setExistingReceiptUrl(null); // Clear existing URL when new file selected
    }
  };

  const removeReceipt = () => {
    setReceiptFile(null);
    setExistingReceiptUrl(null);
    if (fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const uploadReceipt = async (): Promise<string | null> => {
    if (!receiptFile || !user) return existingReceiptUrl;

    setUploadingReceipt(true);
    try {
      const timestamp = Date.now();
      const sanitizedFileName = receiptFile.name.replace(/[^a-zA-Z0-9.-]/g, '_');
      const filePath = `${user.id}/${timestamp}_${sanitizedFileName}`;

      const { error: uploadError } = await supabase.storage
        .from('receipts')
        .upload(filePath, receiptFile);

      if (uploadError) {
        console.error('Upload error:', uploadError);
        throw uploadError;
      }

      // Return file path only (not public URL) - use signed URLs for access
      return filePath;
    } catch (error) {
      console.error('Error uploading receipt:', error);
      toast.error('Fehler beim Hochladen des Belegs.');
      return existingReceiptUrl;
    } finally {
      setUploadingReceipt(false);
    }
  };

  const getFileIcon = () => {
    if (!receiptFile) return null;
    if (receiptFile.type === 'application/pdf') {
      return <FileText className="w-5 h-5 text-red-500" />;
    }
    return <Image className="w-5 h-5 text-blue-500" />;
  };

  return (
    <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-2xl max-h-[90vh] overflow-y-auto">
        <div className="p-6">
          <h2 className="text-2xl font-bold mb-6">Buchung hinzufügen</h2>

          {/* Tabs */}
          <div className="flex gap-2 mb-6">
            <button
              type="button"
              onClick={() => handleTabChange('einnahme')}
              className={`px-6 py-2 rounded-lg font-medium transition-colors ${
                activeTab === 'einnahme'
                  ? 'bg-green-500 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              Einnahme
            </button>
            <button
              type="button"
              onClick={() => handleTabChange('ausgabe')}
              className={`px-6 py-2 rounded-lg font-medium transition-colors ${
                activeTab === 'ausgabe'
                  ? 'bg-red-500 text-white'
                  : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
              }`}
            >
              Ausgabe
            </button>
          </div>

          <form onSubmit={(e) => handleSubmit(e, false)} className="space-y-4">
            {/* Transaction Number and Date */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Beleg-Nr {!transaction && <span className="text-xs text-gray-500">(wird automatisch generiert)</span>}
                </label>
                <input
                  type="text"
                  value={transactionNumber}
                  onChange={(e) => setTransactionNumber(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent bg-gray-50"
                  placeholder="Automatisch"
                  disabled={!transaction}
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Datum
                </label>
                <input
                  type="date"
                  value={date}
                  onChange={(e) => setDate(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent"
                  required
                />
              </div>
            </div>

            {/* Amount and Category */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Betrag (CHF)
                </label>
                <input
                  type="number"
                  step="0.01"
                  value={amount}
                  onChange={(e) => setAmount(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent"
                  required
                />
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Kategorie
                </label>
                <select
                  value={categoryId}
                  onChange={(e) => handleCategoryChange(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent"
                  disabled={isLoadingCategories}
                >
                  {isLoadingCategories ? (
                    <option value="">Lädt...</option>
                  ) : categories.length === 0 ? (
                    <option value="">Keine Kategorien verfügbar</option>
                  ) : (
                    <>
                      {incomeCategories.length > 0 && (
                        <optgroup label="Einnahmen">
                          {incomeCategories.map((cat) => (
                            <option key={cat.id} value={cat.id}>{cat.name}</option>
                          ))}
                        </optgroup>
                      )}
                      {expenseCategories.length > 0 && (
                        <optgroup label="Ausgaben">
                          {expenseCategories.map((cat) => (
                            <option key={cat.id} value={cat.id}>{cat.name}</option>
                          ))}
                        </optgroup>
                      )}
                    </>
                  )}
                </select>
              </div>
            </div>

            {/* Description */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Beschreibung
              </label>
              <textarea
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                rows={3}
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent"
                placeholder="Details zur Buchung..."
              />
            </div>

            {/* Receipt Upload */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Beleg (optional)
              </label>
              <input
                ref={fileInputRef}
                type="file"
                accept=".pdf,.jpg,.jpeg,.png,.webp"
                onChange={handleFileSelect}
                className="hidden"
                id="receipt-upload"
              />

              {!receiptFile && !existingReceiptUrl ? (
                <label
                  htmlFor="receipt-upload"
                  className="flex items-center justify-center gap-2 w-full px-4 py-3 border-2 border-dashed border-gray-300 rounded-lg cursor-pointer hover:border-brand hover:bg-gray-50 transition-colors"
                >
                  <Upload className="w-5 h-5 text-gray-400" />
                  <span className="text-sm text-gray-600">PDF oder Bild hochladen (max. 10 MB)</span>
                </label>
              ) : (
                <div className="flex items-center justify-between px-4 py-3 bg-gray-50 border border-gray-200 rounded-lg">
                  <div className="flex items-center gap-3">
                    {receiptFile ? (
                      <>
                        {getFileIcon()}
                        <span className="text-sm text-gray-700 truncate max-w-[200px]">
                          {receiptFile.name}
                        </span>
                        <span className="text-xs text-gray-500">
                          ({(receiptFile.size / 1024).toFixed(0)} KB)
                        </span>
                      </>
                    ) : existingReceiptUrl ? (
                      <>
                        <FileText className="w-5 h-5 text-green-500" />
                        <button
                          type="button"
                          onClick={async () => {
                            const { data, error } = await supabase.storage
                              .from('receipts')
                              .createSignedUrl(existingReceiptUrl, 60);
                            if (error) {
                              console.error('Error creating signed URL:', error);
                              toast.error('Fehler beim Öffnen des Belegs.');
                              return;
                            }
                            if (data?.signedUrl) {
                              window.open(data.signedUrl, '_blank');
                            }
                          }}
                          className="text-sm text-brand hover:underline"
                        >
                          Beleg anzeigen
                        </button>
                      </>
                    ) : null}
                  </div>
                  <button
                    type="button"
                    onClick={removeReceipt}
                    className="p-1 text-gray-400 hover:text-red-500 transition-colors"
                    title="Beleg entfernen"
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>
              )}
              {uploadingReceipt && (
                <p className="mt-1 text-sm text-gray-500">Beleg wird hochgeladen...</p>
              )}
            </div>

            {/* Customer and Project */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Kund:in wählen (optional)
                </label>
                <select
                  value={customerId}
                  onChange={(e) => setCustomerId(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent"
                >
                  <option value="">-- Keine Auswahl --</option>
                  {customers.map((customer) => (
                    <option key={customer.id} value={customer.id}>
                      {customer.name}
                    </option>
                  ))}
                </select>
              </div>
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Projekt (optional)
                </label>
                <select
                  value={projectId}
                  onChange={(e) => setProjectId(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent"
                >
                  <option value="">-- Keine Auswahl --</option>
                  {projects.map((project) => (
                    <option key={project.id} value={project.id}>
                      {project.name}
                    </option>
                  ))}
                </select>
              </div>
            </div>

            {/* Tags */}
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                Tags (optional)
              </label>
              <div className="flex gap-2 mb-2">
                <input
                  type="text"
                  value={tagInput}
                  onChange={(e) => setTagInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault();
                      addTag();
                    }
                  }}
                  className="flex-1 px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-brand focus:border-transparent"
                  placeholder="Tag hinzufügen..."
                />
                <button
                  type="button"
                  onClick={addTag}
                  className="px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200"
                >
                  Hinzufügen
                </button>
              </div>
              <div className="flex flex-wrap gap-2">
                {tags.map((tag) => (
                  <span
                    key={tag}
                    className="inline-flex items-center gap-1 px-3 py-1 bg-brand text-white rounded-full text-sm"
                  >
                    {tag}
                    <button
                      type="button"
                      onClick={() => removeTag(tag)}
                      className="hover:text-gray-200"
                    >
                      ×
                    </button>
                  </span>
                ))}
              </div>
            </div>

            {/* Buttons */}
            <div className="flex justify-end gap-3 pt-4">
              <button
                type="button"
                onClick={onCancel}
                className="px-4 py-2 text-gray-700 hover:bg-gray-100 rounded-lg"
                disabled={loading}
              >
                Abbrechen
              </button>
              <button
                type="button"
                onClick={(e) => handleSubmit(e, true)}
                className="px-4 py-2 bg-gray-200 text-gray-700 rounded-lg hover:bg-gray-300"
                disabled={loading}
              >
                Speichern & neu
              </button>
              <button
                type="submit"
                className="px-4 py-2 bg-brand text-white rounded-lg hover:bg-opacity-90"
                disabled={loading}
              >
                {loading ? 'Speichern...' : 'Speichern'}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}
